### ISSUE TITLE
need to return database version

### ISSUE THREAD

**Issue by mcfrank** [langcog/childesr#10]
maybe as a `message` with every function call?

**Comment by mcfrank** [comment]
use this functionality in: https://github.com/langcog/childes-db-shiny/issues/6

**Comment by amsan7** [comment]
did we decide whether we wanted db version # to appear after every function call? or was that too spammy? currently we have `get_database_version()` function available. @mikabr

**Comment by mikabr** [comment]
my recollection was that we decided to have a message with the version number with every function call (most functions already give a message about the amount of the data they're retrieving, so it could be integrated with that?)
