### ISSUE TITLE
add get_types and get_speaker_statistics to tutorial

### ISSUE THREAD

**Issue by amsan7** [langcog/childesr#12]
https://langcog.github.io/childesr//articles/access_childes_db.html

**Comment by kemacdonald** [comment]
@amsan7 I added these to the [ package vignette](https://langcog.github.io/childesr//articles/access_childes_db.html). could you take a quick pass to see if it all looks good before we add to the site? thanks!

**Comment by amsan7** [comment]
@kemacdonald looks good!

**Comment by kemacdonald** [comment]
@amsan7 great! added to the site
