### ISSUE TITLE
add "stem" argument to get_tokens

### ISSUE THREAD

**Issue by mikabr** [langcog/childesr#14]
to support use cases like querying `stem="love"` to get tokens `love`, `loves`, `loved`, etc

**Comment by mcfrank** [comment]
figure out how to deal with this cross-linguistically?

**Comment by mcfrank** [comment]
throw informative error if no %mor for this kid

**Comment by mcfrank** [comment]
if any of the transcripts you are querying don't have %mor you need to get info on this. this may require info in the transcripts table about which transcripts have %mor.

**Comment by mikabr** [comment]
I implemented this filter but it's quite slow, presumably because `stem` isn't indexed?@amsan7 could you add an index on it?

**Comment by amsan7** [comment]
added

**Comment by mikabr** [comment]
thanks!
