### ISSUE TITLE
not sure how useful ids are in return value

### ISSUE THREAD

**Issue by amsan7** [langcog/childesr#19]
Does the average user care about ids? They're not very descriptive in terms of which corpus, transcript, or which participant. They're good for avoiding duplicates, if any of these variables happen to be repeated, or for use cases as described in this issue: https://github.com/langcog/childesr/issues/5. But I get the feeling users might want to communicate their needs using corpora_name, speaker_name, transcript_filename, etc. We could provide options for including ids and searching by ids for more advanced users. Thoughts?

**Comment by mcfrank** [comment]
what about adding `return_ids = FALSE` as a default?

also - we could decrease the importance of this feature by unique-ifying the child names on import, e.g. if there are two Adam's, return `Adam (Brown)`...

**Comment by amsan7** [comment]
on second thought i think we should keep id's! related to #5 and #23
