### ISSUE TITLE
token encoding issue

### ISSUE THREAD

**Issue by amsan7** [langcog/childesr#24]
![image](https://user-images.githubusercontent.com/9631010/37484509-f5daddcc-2845-11e8-9b55-ea57c971b174.png)

**Comment by mikabr** [comment]
surprisingly easy fix, see
https://stackoverflow.com/questions/30932708/how-to-change-dplyrtbl-connection-encoding-to-utf8
https://github.com/r-dbi/RMySQL/issues/2
