### ISSUE TITLE
age argument in get_utterances

### ISSUE THREAD

**Issue by mllewis** [langcog/childesr#27]
Doesn't work for me.

This works: 
`get_utterances(collection = "Eng-NA", 
                       corpus = "Clark", 
                       role = "Target_Child",
                       child = "Shem")`

This does not:
`get_utterances(collection = "Eng-NA", 
                       corpus = "Clark", 
                       role = "Target_Child",
                       child = "Shem",
                       age = 807.375)`

**Comment by amsan7** [comment]
I think the age parameter has to be in months

**Comment by mllewis** [comment]
Oh gotcha....it’s just confusing because the function returns age in days.

**Comment by amsan7** [comment]
yeah true... think we address this here https://github.com/langcog/childesr/issues
