### ISSUE TITLE
corpus argument error

### ISSUE THREAD

**Issue by anordmey** [langcog/childesr#31]
The corpus argument isn't working for me for any of the functions. 

For example, this (from the tutorial):

```
d_brown_transcripts <- get_transcripts(collection = NULL, 
                                       corpus = "Brown", 
                                       child = NULL)
```

returns this error: 
```
Error in .local(conn, statement, ...) : 
  could not run statement: Unknown column 'corpus_name' in 'where clause'
```

Including the corpus argument returns the same error for all functions: get_participants(), get_tokens(), get_types(), get_utterances(), get_speaker_statistics()

**Comment by kemacdonald** [comment]
Hey @anordmey! I know there were some recent updates to the package. Could you try reinstalling with `devtools::install_github("langcog/childesr")` to see if that fixes things?

**Comment by anordmey** [comment]
That worked, thanks @kemacdonald!

**Comment by kemacdonald** [comment]
Great!
