### ISSUE TITLE
Unicode-Problem

### ISSUE THREAD

**Issue by GerlindGrosse** [langcog/childesr#42]
Hi! I can't resolve the following error:

The problem is the "ü" in German. How is it encoded in the original data base?

Error-Message:
Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation 'like'

Here is the code:
gruen_all <- get_tokens(collection="German", role = c("mother", "father"), token = c("grün", "grüne", "grüner","grünes", "grünen", "grünem"))
hist(gruen_all$target_child_age)
describe(gruen_all$target_child_age)

Thanks for your help!

**Comment by smeylan** [comment]
`gruen_all <- get_tokens(collection="German", role = c("mother", "father"), token = c("grün", "grüne", "grüner","grünes", "grünen", "grünem"))` works for me in R 3.4.2 on OS X 10.14.6, which makes me think it is specific to the client environment. What version of R, IDE, and platform are you using?
