### ISSUE TITLE
Can't connect to MySQL server

### ISSUE THREAD

**Issue by jinyoungjo** [langcog/childesr#43]
Hello,

Using the childesr package for the first time, I encountered this error message while trying to run the following code:

utt <- get_utterances(corpus = "Brown", target_child = "Adam")

Error in .local(drv, ...) : 
  Failed to connect to database: Error: Can't connect to MySQL server on 'ec2-54-68-171-132.us-west2.compute.amazonaws.com' (0)

Could anyone identify what the problem is?

Thanks in advance!

**Comment by smeylan** [comment]
We see this most often when people try to access the database from a guest network at a university or from a coffeeshop where the firewall limits traffic on certain ports. Is either of these the case?

We should probably have some error-catching code on the R client that checks another MySQL server to see if it is a more general MySQL problem

**Comment by jinyoungjo** [comment]
Yes, I was using the university wifi, so that should have been the problem. Thank you for your reply!
