### ISSUE TITLE
Add new columns to support childes-db 2020.1

### ISSUE THREAD

**Issue by JMankewitz** [langcog/childesr#45]
We added the following columns (all dtypes are characters):
`source` under the `corpus` table
`pho` and `mod` under the `utterance` table
`pho` and `mod` under the `token` table

**Comment by mikabr** [comment]
are `pho` and `mod` actually called `actual_phonology` and `model_phonology`?

**Comment by JMankewitz** [comment]
Yep! Sorry, was looking at the previous django model

**Comment by mikabr** [comment]
ok great, package should be all set then (it actually only enforces column names minimally, i.e. only primary keys and foreign keys, basically)
