### ISSUE TITLE
getting utterances/words by id

### ISSUE THREAD

**Issue by mcfrank** [langcog/childesr#5]
this is useful for when you want to get something for a user-defined participant group (e.g., males with more than 10 transcripts). but it's also complicated with respect to backend behavior. discuss.

**Comment by amsan7** [comment]
interesting point. you can technically still do this with current API, but you would have to pull in all utterances locally and then apply the filter (or you can just open a connection yourself). it also makes me think about whether users would want to search by any other column not included in our API spec - for ex, stem in utterances (for regex etc). you can argue that the API provides the simplest / basic functionality, but if you really wanted to, you can open a connection yourself to perform the db-side computations. Maybe this is a question of whether querying utterances / tokens by id is a basic use case.

side note: id's (primary keys) aren't guaranteed to be the same across versions, so we might need to communicate that somehow
