### ISSUE TITLE
unable to retrieve all tokens from a child

### ISSUE THREAD

**Issue by amsan7** [langcog/childesr#9]
`get_tokens` has no default when `token` param isn't specified

**Comment by dyurovsky** [comment]
Good point. We decided not to let people search for all tokens because it takes too long, but maybe we should allow this within child or corpus? What do you think @mikabr ?

**Comment by mcfrank** [comment]
How about if we throw an error ("that'll take too long! confirm that you
want *all* the tokens by supplying * as the token specifier.")


Mike

**Comment by mikabr** [comment]
I agree with Mike, how about something like `Error: Argument "token" is missing. To fetch all tokens, supply "*" for argument "token". Caution: this may result in a long-running query.`
